### ISSUE TITLE
下載不了種子

### ISSUE THREAD

**Issue by mic4126** [exzhawk/EhViewer#10]
**简略描述 / Describe the bug**
大概说下是什么问题。

Cannot download torrent
下載不了torrent

**如何重现 / To Reproduce**
重现的步骤：
1. 打开 /g/1680376/7074d3bc97/
2. 点击 種子
3. 出现了奇怪的錯誤

**预期行为 / Expected behavior**
应该是什么样子的？ 顯示種子 or 沒有

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：Xperia 1
 - Android 版本：10

**备注 / Additional context**
还有什么想说的？

**Comment by mic4126** [comment]
Part of the logcat

```
07-21 16:28:25.405 31442 31477 D EhEngine: https://exhentai.org/?f_cats=1021&f_stags=on&f_sh=on&f_search=language%3Achinese&f_sname=on&advsearch=1&f_sr=on&f_srdd=3
07-21 16:28:28.432 31442 31469 D EhEngine: https://exhentai.org/?f_cats=1019&f_stags=on&f_search=language%3Achinese&f_sname=on&advsearch=1&f_sr=on&f_srdd=3
07-21 16:28:32.380 31442 31476 D EhEngine: https://exhentai.org/?f_cats=1015&f_search=language%3Achinese+
07-21 16:28:35.787 31442 31457 W System  : A resource failed to call close. 
07-21 16:28:35.787 31442 31457 I chatty  : uid=10421(com.hippo.ehviewer) FinalizerDaemon identical 14 lines
07-21 16:28:35.787 31442 31457 W System  : A resource failed to call close. 
07-21 16:28:36.549 31442 32595 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
07-21 16:28:44.612 31442 31442 I FloatingActionButton: Setting a custom background is not supported.
07-21 16:28:44.613 31442 31442 I chatty  : uid=10421(com.hippo.ehviewer) identical 1 line
07-21 16:28:44.614 31442 31442 I FloatingActionButton: Setting a custom background is not supported.
07-21 16:28:44.615 31442 31442 I FloatingActionButton: Setting a custom background is not supported.
07-21 16:28:44.635 31442 32595 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
07-21 16:28:48.358 31442 31477 D EhEngine: https://exhentai.org/?f_cats=1015&f_search=language%3Achinese+
07-21 16:28:56.372 31442 31469 D EhEngine: https://exhentai.org/g/1688863/a173491dda/
07-21 16:28:56.391 31442 32595 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
07-21 16:28:56.745 31442 31457 W System  : A resource failed to call close. 
07-21 16:28:56.746 31442 31457 I chatty  : uid=10421(com.hippo.ehviewer) FinalizerDaemon identical 7 lines
07-21 16:28:56.746 31442 31457 W System  : A resource failed to call close. 
07-21 16:28:59.175 31442 31476 D EhEngine: 
07-21 16:28:59.197 31442 31442 W System.err: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
07-21 16:28:59.202 31442 31442 W System.err: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
07-21 16:28:59.202 31442 31442 W System.err: 	at okhttp3.HttpUrl.get(HttpUrl.java:916)
07-21 16:28:59.202 31442 31442 W System.err: 	at okhttp3.Request$Builder.url(Request.java:165)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.okhttp.ChromeRequestBuilder.<init>(ChromeRequestBuilder.java:34)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.ehviewer.client.EhRequestBuilder.<init>(EhRequestBuilder.java:28)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.ehviewer.client.EhRequestBuilder.<init>(EhRequestBuilder.java:24)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.ehviewer.client.EhEngine.getTorrentList(EhEngine.java:652)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.ehviewer.client.EhClient$Task.doInBackground(EhClient.java:163)
07-21 16:28:59.202 31442 31442 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
07-21 16:28:59.202 31442 31442 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 16:28:59.202 31442 31442 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 16:28:59.202 31442 31442 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 16:28:59.202 31442 31442 W System.err: 	at java.lang.Thread.run(Thread.java:919)
07-21 16:28:59.202 31442 31442 W System.err: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
07-21 16:28:59.203 31442 31442 W DecorView[]: The visibility of the navigation bar is low, color=ffffffff, hasLightNavBar=true, isFloating=true
07-21 16:29:00.483 31442 31442 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
07-21 16:29:02.773 31442 31442 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5a16650
07-21 16:29:02.780 31442 32595 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
07-21 16:29:05.292 31442 31457 W System  : A resource failed to call close. 
07-21 16:29:05.292 31442 31457 I chatty  : uid=10421(com.hippo.ehviewer) FinalizerDaemon identical 5 lines
07-21 16:29:05.292 31442 31457 W System  : A resource failed to call close. 
```

**Comment by exzhawk** [comment]
fixed in version 1.7.6
https://github.com/exzhawk/EhViewer/releases/tag/1.7.6
